# Generated by Django 2.2.7 on 2019-12-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_auto_20191201_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['vote_score']},
        ),
    ]
